/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.smart_home.ui;

import com.mycompany.smart_home.models.AccessLog;
import com.mycompany.smart_home.service.DeviceService;
import com.mycompany.smart_home.service.impl.DeviceServiceImpl;
import com.mycompany.smart_home.service.MqttService;
import com.mycompany.smart_home.models.Device;
import com.mycompany.smart_home.models.EnvironmentLog;
import com.mycompany.smart_home.service.AccessLogService;
import com.mycompany.smart_home.service.EnvironmentLogService;
import com.mycompany.smart_home.service.impl.AccessLogServiceImpl;
import com.mycompany.smart_home.service.impl.EnvironmentLogServiceImpl;
import com.mycompany.smart_home.service.mqtt.DeviceStatusMessageHandler;
import com.mycompany.smart_home.service.mqtt.EnvironmentMessageHandler;
import com.mycompany.smart_home.service.mqtt.RfidMessageHandler;

import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import static javax.swing.JOptionPane.showConfirmDialog;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import static org.jfree.chart.ChartFactory.createLineChart;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import com.mycompany.smart_home.models.AlertLog;
import com.mycompany.smart_home.service.AlertLogService;
import com.mycompany.smart_home.service.impl.AlertLogServiceImpl;
/**
 *
 * @author long3
 */
public class MainDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainDashboard.class.getName());
    //private static final String UNKNOWN_MAC = "-";
    
    private DeviceService deviceService = new DeviceServiceImpl();
    private AccessLogService accessLogService = new AccessLogServiceImpl();
    private EnvironmentLogService envService = new EnvironmentLogServiceImpl();
    
    private MqttService mqtt;
    
    public void updateEnvironmentParametersString (String temperature, String humidity) {
        SwingUtilities.invokeLater(() -> {
            lblTemperature.setText(temperature + " °C");
            lblHumidity.setText(humidity + " %");
        });
    }
    /**
     * Creates new form MainDashboard
     */
    // ... (Giữ nguyên các biến cũ)
    private AlertLogService alertLogService = new AlertLogServiceImpl(); // THÊM DÒNG NÀY

    // TÌM VÀ SỬA LẠI HÀM CONSTRUCTOR NHƯ SAU:
    public MainDashboard() {
        initComponents();
        initAlertLogTab(); // Khởi tạo Tab cảnh báo (code giao diện bằng tay)
        this.setLocationRelativeTo(null); 
        
        mqtt = new MqttService();
        mqtt.addHandler(new EnvironmentMessageHandler(this));
        mqtt.addHandler(new RfidMessageHandler(this, mqtt));
        mqtt.addHandler(new DeviceStatusMessageHandler());
        mqtt.start();
        
        loadDevicesToTable();
        loadAccessLogsToTable();
        loadAlertLogsToTable(); // Tải dữ liệu cảnh báo lên bảng
        drawEnvironmentalGraph();
    }
    // ...

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDevices = new javax.swing.JTable();
        btnDeleteDevice = new javax.swing.JButton();
        btnAddDevice1 = new javax.swing.JButton();
        btnTogglePower = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        tblAccessLogs = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTemperature = new javax.swing.JLabel();
        lblHumidity = new javax.swing.JLabel();
        pnlChart = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        btnMqtt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smart Home Application");

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI Emoji", 3, 12)); // NOI18N

        tblDevices.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        tblDevices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Device ID", "Device Name", "Device Type", "Mqtt Topic", "Devices Status"
            }
        ));
        jScrollPane1.setViewportView(tblDevices);

        btnDeleteDevice.setBackground(new java.awt.Color(255, 102, 102));
        btnDeleteDevice.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        btnDeleteDevice.setText("Delete Device");
        btnDeleteDevice.addActionListener(this::btnDeleteDeviceActionPerformed);

        btnAddDevice1.setBackground(new java.awt.Color(102, 255, 102));
        btnAddDevice1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        btnAddDevice1.setText("Add Device");
        btnAddDevice1.addActionListener(this::btnAddDevice1ActionPerformed);

        btnTogglePower.setBackground(new java.awt.Color(255, 255, 153));
        btnTogglePower.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        btnTogglePower.setText("ON/OFF");
        btnTogglePower.addActionListener(this::btnTogglePowerActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnAddDevice1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDeleteDevice)
                .addGap(67, 67, 67)
                .addComponent(btnTogglePower)
                .addGap(55, 55, 55))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddDevice1)
                    .addComponent(btnTogglePower)
                    .addComponent(btnDeleteDevice))
                .addGap(46, 46, 46))
        );

        jTabbedPane1.addTab("Device Management", jPanel2);

        tblAccessLogs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Access Id", "Rfid Tag", "User Id", "Access Status", "Accessed At"
            }
        ));
        jScrollPane.setViewportView(tblAccessLogs);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Access Logs", jPanel3);

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 3, 24)); // NOI18N
        jLabel1.setText("Temperature:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 3, 24)); // NOI18N
        jLabel2.setText("Humidity:");

        lblTemperature.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        lblTemperature.setText("0 °C");

        lblHumidity.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        lblHumidity.setText("0 %");

        javax.swing.GroupLayout pnlChartLayout = new javax.swing.GroupLayout(pnlChart);
        pnlChart.setLayout(pnlChartLayout);
        pnlChartLayout.setHorizontalGroup(
            pnlChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );
        pnlChartLayout.setVerticalGroup(
            pnlChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHumidity, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTemperature)
                    .addComponent(lblHumidity)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Overview", jPanel1);

        btnLogout.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        btnMqtt.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        btnMqtt.setText("MQTT");
        btnMqtt.addActionListener(this::btnMqttActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMqtt)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogout)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout)
                    .addComponent(btnMqtt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTogglePowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTogglePowerActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDevices.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Chọn một thiết bị");
            return;
        }

        int deviceId = (int) tblDevices.getValueAt(selectedRow, 0);
        String topic = (String) tblDevices.getValueAt(selectedRow, 4);
        String currentStatus = (String) tblDevices.getValueAt(selectedRow, 5);

        String newCommand = currentStatus.equals("ON") ? "OFF" : "ON";

        mqtt.publishCommand(topic + "/control", newCommand);

        deviceService.changeDeviceStatus(deviceId, newCommand);

        loadDevicesToTable();
    }//GEN-LAST:event_btnTogglePowerActionPerformed

    private void btnAddDevice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDevice1ActionPerformed
        // TODO add your handling code here:
        JTextField txtName = new JTextField();

        JComboBox<String> cbType = new JComboBox<>(new String[]{"Light", "Door", "Sensor"});
        JTextField txtTopic = new JTextField();

        JPanel panel = new JPanel(new java.awt.GridLayout(3, 2, 5, 5));
        panel.add(new JLabel("Device Name:"));
        panel.add(txtName);
        panel.add(new JLabel("Device Type:"));
        panel.add(cbType);
        panel.add(new JLabel("MQTT Topic:"));
        panel.add(txtTopic);

        int result = JOptionPane.showConfirmDialog(this, panel,
            "Add Device", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            String name = txtName.getText().trim();
            String type = cbType.getSelectedItem().toString();
            String topic = txtTopic.getText().trim();

            if (name.isEmpty() || topic.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không để trống thông tin!", "Lỗi", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Device newDevice = new Device();
            newDevice.setDeviceName(name);
            newDevice.setDeviceType(type);
            newDevice.setMqttTopic(topic);
            newDevice.setCurrentStatus("OFF");

            boolean success = deviceService.addDevice(newDevice);

            if (success) {
                JOptionPane.showMessageDialog(this, "Đã thêm thiết bị thành công!");
                loadDevicesToTable();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại!", "Lỗi CSDL", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnAddDevice1ActionPerformed

    private void btnDeleteDeviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDeviceActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDevices.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Chọn một thiết bị trên bảng để xóa!");
            return;
        }

        int deviceId = (int) tblDevices.getValueAt(selectedRow, 0);
        String deviceName = (String) tblDevices.getValueAt(selectedRow, 1);

        int confirm = JOptionPane.showConfirmDialog(this,
            "Chắc chắn muốn xóa thiết bị: " + deviceName + "?", "Xác nhận xóa",
            JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            boolean success = deviceService.deleteDevice(deviceId);

            if (success) {
                JOptionPane.showMessageDialog(this, "Đã xóa thành công!");
                loadDevicesToTable();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại. Vui lòng thử lại!");
            }
        }
    }//GEN-LAST:event_btnDeleteDeviceActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int confirm = showConfirmDialog(this, "Bạn có muốn đăng xuất?", "Xác nhận Đăng xuất", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        // Nếu người dùng chọn YES
        if (confirm == JOptionPane.YES_OPTION) {
            
            if (this.mqtt != null) {
                this.mqtt.stop(); 
            }

            com.mycompany.smart_home.ui.LoginFrame loginFrame = new com.mycompany.smart_home.ui.LoginFrame();
            loginFrame.setLocationRelativeTo(null); 
            loginFrame.setVisible(true);

            this.dispose(); 
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnMqttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMqttActionPerformed
        // TODO add your handling code here:
        if (this.mqtt != null && this.mqtt.isConnected()) {
            JOptionPane.showMessageDialog(this, "Mạng MQTT đang KẾT NỐI", "Trạng thái Mạng", JOptionPane.INFORMATION_MESSAGE);    
        } else {
            JOptionPane.showMessageDialog(this, "LỖI: Mất kết nối MQTT!", "Lỗi Mạng", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnMqttActionPerformed
    private void loadDevicesToTable() {
        DefaultTableModel model = (DefaultTableModel) tblDevices.getModel();
        model.setRowCount(0); 
        
        List<Device> listDevices = deviceService.getAllDevices();
        
        for (Device dev : listDevices) {
            Object[] row = new Object[]{
                dev.getDeviceId(),
                dev.getDeviceName(),
                dev.getDeviceType(),
                //UNKNOWN_MAC,
                dev.getMqttTopic(),
                dev.getCurrentStatus()
            };
            model.addRow(row);
        }
    }
    
    public void loadAccessLogsToTable() {
        DefaultTableModel model = (DefaultTableModel) tblAccessLogs.getModel();
        model.setRowCount(0);
        
        java.util.List<AccessLog> listLogs = accessLogService.getAllAccessHistory();
        
        for (AccessLog log : listLogs) {
            Object[] row = new Object[]{
                log.getAccessId(),
                log.getRfidTag(),
                log.getUserId(), 
                log.getAccessStatus(),
                log.getAccessedAt()
            };
            model.addRow(row);
        }
    }
    
    public void drawEnvironmentalGraph() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        
        List<EnvironmentLog> list = envService.getLogsForChart(15); 
        
        for (EnvironmentLog log : list) {
            String time = log.getRecordedAt().toString().substring(11, 16); 
            
            dataset.addValue(log.getTemperature(), "Nhiệt độ (°C)", time);
            dataset.addValue(log.getHumidity(), "Độ ẩm (%)", time);
        }

        JFreeChart chart = createLineChart("Biến Thiên Nhiệt Độ & Độ Ẩm", "Thời gian", "Giá trị",
                                            dataset,
                                            PlotOrientation.VERTICAL, 
                                            true, true, false);

        ChartPanel chartPanel = new org.jfree.chart.ChartPanel(chart);
        pnlChart.removeAll();
        pnlChart.setLayout(new java.awt.BorderLayout());
        pnlChart.add(chartPanel, java.awt.BorderLayout.CENTER);
        pnlChart.validate();
        pnlChart.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainDashboard().setVisible(true));
    }
    // THÊM 2 HÀM NÀY VÀO TRƯỚC HÀM main() HOẶC CUỐI CLASS
    private javax.swing.JPanel jPanelAlerts;
    private javax.swing.JScrollPane jScrollPaneAlerts;
    private javax.swing.JTable tblAlertLogs;

    private void initAlertLogTab() {
        tblAlertLogs = new javax.swing.JTable();
        tblAlertLogs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {"ID", "Thời gian", "Loại", "Giá trị đo", "Nội dung"}
        ));
        jScrollPaneAlerts = new javax.swing.JScrollPane();
        jScrollPaneAlerts.setViewportView(tblAlertLogs);
        
        jPanelAlerts = new javax.swing.JPanel();
        jPanelAlerts.setLayout(new java.awt.BorderLayout());
        jPanelAlerts.add(jScrollPaneAlerts, java.awt.BorderLayout.CENTER);
        
        jTabbedPane1.addTab("Alert Logs", jPanelAlerts);
    }

    public void loadAlertLogsToTable() {
        if (tblAlertLogs != null) {
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblAlertLogs.getModel();
            model.setRowCount(0); 
            java.util.List<AlertLog> listLogs = alertLogService.getAllAlertLogs();
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("HH:mm:ss dd/MM");
            
            for (AlertLog log : listLogs) {
                Object[] row = new Object[]{
                    log.getAlertId(),
                    sdf.format(log.getCreatedAt()),
                    log.getAlertType(),
                    log.getActualValue() + " °C",
                    log.getMessage()
                };
                model.addRow(row);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDevice1;
    private javax.swing.JButton btnDeleteDevice;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMqtt;
    private javax.swing.JButton btnTogglePower;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblHumidity;
    private javax.swing.JLabel lblTemperature;
    private javax.swing.JPanel pnlChart;
    private javax.swing.JTable tblAccessLogs;
    private javax.swing.JTable tblDevices;
    // End of variables declaration//GEN-END:variables
}
